import express from "express";
import Models from "felixriddle.mongodb-models";
import bodyParser from "body-parser";
import cookieParser from "cookie-parser";

import mainRouter from "@/routes";
import { jwtToken } from "@/config/env";

/**
 * Run express server
 */
export default function runExpressServer(models: Models, port: number) {
	const app = express();
	
	app.use(bodyParser.urlencoded({ extended: true }));
	app.use(bodyParser.json());
	
	app.use(cookieParser(jwtToken()));

	app.use(mainRouter(models));
	
	app.listen(port, () => {
		// Tabnine autogenerated
		console.log(`Server running on port ${port}`);
		
        console.log("Press Ctrl+C to stop the server");
        process.on("SIGINT", () => {
            console.log("Server stopped");
            process.exit(0);
        });
        process.on("SIGTERM", () => {
            console.log("Server stopped");
            process.exit(0);
        });
        process.on("SIGUSR2", () => {
            console.log("Server stopped");
            process.exit(0);
        });
        process.on("uncaughtException", (err) => {
            console.error("Uncaught exception", err);
            process.exit(1);
        });
	});
}
